### ISSUE TITLE
delete region prevents redraw of any further created regions

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#76] opened 2021-01-01 20:07 UTC
If you delete a region, then create a new one, the list of regions doesn't update and show the newly created region. This region is however created as you can exit to the main transcription list and re-enter the transcription and the newly created region is there.

**Comment by aaronfay** [comment] 2021-01-01 20:47
I can't reproduce this locally, @bengodden is this on the Barry Ahenakew transcription?

**Comment by bengodden** [comment] 2021-01-01 22:04
Yeah, this happened on the Barry ahenakew file. create a region at the end of what is done. Delete it. The recreate it. Try resizing it or shift it on the timeline. then try to input text.

**Comment by aaronfay** [comment] 2021-01-11 00:22
I wonder if there was a hidden network error on that particular region save that caused script execution to halt. I'm going to close this for now (as I still can't reproduce) in favor of https://github.com/kiyanaw/kiyanaw-backend/issues/76

**Comment by bengodden** [comment] 2021-01-11 09:57
![kiyanaw_bug76_screenshot](https://user-images.githubusercontent.com/57279900/104166696-69db4e00-53b8-11eb-842e-fcdc9e047cc3.png)
![kiyanaw_bug76_error](https://user-images.githubusercontent.com/57279900/104166698-6c3da800-53b8-11eb-803e-996ae9111322.png)

Hey, I'm still getting this error. I've posted a screenshot of the redraw (notice that the last region is shown on the waveform editor but not the region list. That last region exists, and If I exit the transcription and re-enter it, that region will show up on the list of regions. There was an error in the console. I've posted a picture of that as well.

**Comment by bengodden** [comment] 2021-01-11 10:02
Ignore this bug. I'm closing it again. Simply scrolling on the list of regions will redraw the missing region(s).

**Comment by aaronfay** [comment] 2021-01-11 17:11
I wonder if it's an issue on the Barry Ahenakew video specifically. Can we jump in a call on this one some time @bengodden ?

**Comment by aaronfay** [comment] 2021-07-24 04:04
I think this has been fixed, closing.

**Closed by aaronfay** 2021-07-24 04:04 UTC
Labels: bug, transcibe-editor
